from django.urls import path

from . import views

urlpatterns = [
    path("login", views.login, name="login"),
    path("signup", views.signup, name='signup'),
    path("getitems", views.get_cart_items, name='getitems'),
    path("removeFromCart", views.removeFromCart, name='removeFromCart'),
    path("addresses_all", views.getAddressesOfUser, name="addresses_all"),
    path("order", views.order, name="order"),
    path("getProducts", views.getProducts, name="getProducts"),
    path('products/<str:_id>', views.productDetail, name='productDetail'),
    path("register-invoice", views.register_invoice, name="register_invoice"),
    path("addComment", views.addComment, name='addComment'),
    path("getComments/<str:_id>", views.getComments, name="getComments"),
    path("changeAmount", views.changeAmount, name="changeAmount"),
    path("getUserType", views.getUserType, name="getUserType"),
    path("approveComment", views.approveComment, name="approveComment"),
    path("addToCart", views.addToCart, name="addToCart"),
    path("get_orders", views.get_orders, name="get_orders"),
    path("rate", views.rate, name="rate"),
    path("comment", views.comment, name="comment"),
    path("declineComment", views.declineComment, name="declineComment"),
    path("clearCart", views.clearCart, name="clearCart"),
    path("mergeLocalCart", views.mergeLocalCart, name="mergeLocalCart"),
    path("address", views.address, name="add_address"),
    path("addWishlist", views.addWishlist, name="addWishlist"),
    path("addCustomertoProductWishlist", views.addCustomertoProductWishlist, name="addCustomertoProductWishlist"),
    path("getProfit/<str:startDate>/<str:endDate>", views.getProfit, name="getProfit"),
    path("changeStock", views.changeStock, name="changeStock"),
    path("getWishlist", views.getWishlist, name="getWishlist"),
    path("invoice", views.invoice, name="invoice"),
    path("product", views.product, name="product"),
    path("category", views.category, name="category"),
    path("updateProduct/<str:_id>", views.updateProduct, name="updateProduct"),
    path("notifyWishlistCustomers", views.notifyWishlistCustomers, name="notifyWishlistCustomers"),
    path("getApprovalComments", views.getApprovalComments, name="getApprovalComments"),
    path("deleteOrder", views.deleteOrder, name="deleteOrder"),
    path("getRefunds", views.getRefunds, name="getRefunds"),
    path("getProfileInfo", views.getProfileInfo, name="getProfileInfo"),
    path("moreProfileInfo", views.moreProfileInfo, name="moreProfileInfo"),
    path("getAllOrders", views.getAllOrders, name="getAllOrders"),
    path("changeDeliverySta", views.changeDeliverySta, name="changeDeliverySta"),
    path("changeRefundSta", views.changeRefundSta, name="changeRefundSta")
]